### ISSUE TITLE
css tricks

### ISSUE THREAD

**Issue by tiancheng91** [tiancheng91/collection#5]
## frameworks
- https://picturepan2.github.io/spectre/index.html 轻量

##

**Comment by tiancheng91** [comment]
```css
// reset
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}

```

**Comment by tiancheng91** [comment]
```css
position: absolute;
left: 50%;
top: 50%;
transform: transform(-50%, -50%);
```

**Comment by tiancheng91** [comment]
```css
.wrapper > div {
  background: #eee;
  padding: 1em;
}
.wrapper > div:nth-child(odd) {
  background: #ddd;
}
```

**Comment by tiancheng91** [comment]
[grid doc](https://tympanus.net/codrops/css_reference/grid/)

```html
<body>
  <header>...</header>
  <main>...</main>
  <nav>...</nav>
  <aside>...</aside>
  <footer>...</footer>
</body>
```
```css
body { 
  display: grid;
  grid: "header header"
        "nav nav"
        "content sidebar"
        "footer footer";
  grid-template-columns: 1fr 25%; 
}

header { grid-area: header; }
nav { grid-area: nav; }
footer { grid-area: footer; }
```

**Comment by tiancheng91** [comment]
```
animation: fade-in .8s ease-out forwards;
transform: translateY(1em);
```

**Comment by tiancheng91** [comment]
```css
html, body {height:100%}
height: 100vh;
width: 95vw;
```
