### ISSUE TITLE
gitlab ci push时自动取消运行任务

### ISSUE THREAD

**Issue by tiancheng91** [tiancheng91/collection#56]
```yaml
check git head:
  stage: pre-build
  before_script:
    - 'FOR /F "tokens=* USEBACKQ" %%F IN (`git rev-parse HEAD`) DO (SET HEAD_COMMIT=%%F)'
  script: 
    - 'IF NOT %HEAD_COMMIT%==%CI_COMMIT_SHA% curl -X POST --HEADER "PRIVATE-TOKEN: %PRIVATE_API_TOKEN%" https://gitlab.com/api/v4/projects/%CI_PROJECT_ID%/pipelines/%CI_PIPELINE_ID%/cancel'
```
