### ISSUE TITLE
netplan

### ISSUE THREAD

**Issue by tiancheng91** [tiancheng91/collection#65]
```yaml
# This is the network config written by 'subiquity'
network:
  ethernets:
    eth0:
      addresses:
      - 192.168.0.11/24
      gateway4: 192.168.0.10
      nameservers:
        addresses:
        - 192.168.0.10
        search: []
  version: 2
```

```yaml
# dhcp 
network:
  version: 2
  renderer: networkd
  ethernets:
    enp3s0:
      dhcp4: true
```
