### ISSUE TITLE
rscss style

### ISSUE THREAD

**Issue by tiancheng91** [tiancheng91/collection#68]
```scss
// global.scss
$primary-color: #007bff;

body {
  font-family: Arial, sans-serif;
  color: #333;
  background-color: #fff;
}

a {
  color: $primary-color;
  text-decoration: none;
}

// layout.scss
.container {
  max-width: 1200px;
  margin: 0 auto;
}

.row {
  display: flex;
  flex-wrap: wrap;
}

.col {
  flex: 1;
}

// components/header/header.scss
.header {
  background-color: #fff;
  padding: 10px;
}

.header__logo {
  font-size: 24px;
  font-weight: bold;
}

.header__nav {
  margin-left: auto;
}

.header__nav-item {
  display: inline-block;
  margin-left: 10px;
}

// pages/home/home.scss
.home-hero {
  background-image: url('hero.jpg');
  background-size: cover;
  height: 500px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.home-hero__title {
  font-size: 48px;
  color: #fff;
  text-shadow: 0px 2px 4px rgba(0,0,0,0.5);
}

.home-features {
  margin-top: 50px;
}

.home-feature {
  text-align: center;
}

.home-feature__icon {
  font-size: 64px;
  color: $primary-color;
}

.home-feature__title {
  font-size: 24px;
  font-weight: bold;
}

.home-feature__description {
  margin-top: 10px;
}
```
